//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscuelaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notas
    {
        public int idnota { get; set; }
        public Nullable<float> nota1 { get; set; }
        public Nullable<float> nota2 { get; set; }
        public Nullable<float> nota3 { get; set; }
        public Nullable<float> promedio { get; set; }
        public string estado { get; set; }
    }
}
